In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./fraudTrain.csv", index_col=0)

In [3]:
df.head()

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [4]:
from datetime import date

df['dob'] = pd.to_datetime(df['dob'])
today = pd.to_datetime(date.today())
df['age'] = (today - df['dob']).dt.days // 365

In [5]:
date_time = pd.to_datetime(df['trans_date_trans_time'], format='%Y-%m-%d %H:%M:%S')

df['day_of_week'] = date_time.dt.day_of_week
df['day_of_month'] = date_time.dt.day
df['time_of_day'] = date_time.dt.hour
df['month'] = date_time.dt.month

In [6]:
df.drop(columns=["first","last","gender","trans_num","unix_time","merch_lat","merch_long",'trans_date_trans_time',"cc_num","lat","long","city_pop","zip","dob"] , inplace=True)

In [7]:
df.head()

,merchant,category,amt,street,city,state,job,is_fraud,age,day_of_week,day_of_month,time_of_day,month
0,"fraud_Rippin, Kub and Mann",misc_net,4.97,561 Perry Cove,Moravian Falls,NC,"Psychologist, counselling",0,38,1,1,0,1
1,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,43039 Riley Greens Suite 393,Orient,WA,Special educational needs teacher,0,47,1,1,0,1
2,fraud_Lind-Buckridge,entertainment,220.11,594 White Dale Suite 530,Malad City,ID,Nature conservation officer,0,64,1,1,0,1
3,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,9443 Cynthia Court Apt. 038,Boulder,MT,Patent attorney,0,59,1,1,0,1
4,fraud_Keeling-Crist,misc_pos,41.96,408 Bradley Rest,Doe Hill,VA,Dance movement psychotherapist,0,40,1,1,0,1

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from category_encoders import JamesSteinEncoder
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

one_hot_encodable = ["category","state"]
target_encodable = ["merchant","city","street","job"]


preprocessor = ColumnTransformer(
    transformers=[
        ('num', JamesSteinEncoder(), target_encodable),
        ('cat', OneHotEncoder(), one_hot_encodable)
    ],
    remainder='passthrough'  # Options: 'drop' (default) or 'passthrough'
)